openapi: 3.0.1
info:
  title: ceyloanAgri
  description: API Definition of ceyloanAgri
  version: 1.0.0
servers:
- url: http://localhost:8290/ceyloan-agri
paths:
  /:
    get:
      responses:
        default:
          description: Default response
